name: Node.js Du-Lua

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        NPM_CONFIG_PREFIX: "~/.npm-global"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm i -g @wolfe-labs/du-luac
      - run: ~/.npm-global/bin/du-lua build